name: projectuasv2
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  # Menggunakan format standar untuk rentang versi SDK
  sdk: '>=3.4.3 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  
  # Hapus duplikat dan gunakan versi terbaru
  intl: ^0.19.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  http: ^1.2.2

# dev_dependencies dipindahkan ke level yang benar (sejajar dengan dependencies)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"    # Nama ikon untuk Android
  ios: true                   # Aktifkan untuk iOS
  image_path: "assets/images/icon.png" # Path ke file ikon Anda
    

flutter:
  uses-material-design: true

  assets:
    # Hapus path aset yang duplikat
    - assets/images/iconlogin.png
    - assets/images/google.png
    - assets/images/lock.png
    - assets/images/logo.png
    - assets/images/user.png
    - assets/images/kursi1.png
    - assets/images/profile.png
    - assets/images/categories.png
    - assets/images/cart.png
    - assets/images/pay.png
    - assets/images/icon.png
    
  # Perbaikan indentasi pada bagian font (jika nanti akan digunakan)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/font/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600